
### Subchart Configurations

prometheus-operator:
  prometheusOperator:
    admissionWebhooks:
      enabled: false
    createCustomResource: false
    tlsProxy:
      enabled: false

  grafana:
    adminUser: grafanaadmin
    adminPassword: telemetry
